"""Small reference data the converters read at runtime."""
from __future__ import annotations

import gzip
from functools import lru_cache
from pathlib import Path

_HERE = Path(__file__).resolve().parent


@lru_cache(maxsize=1)
def bedrock_vanilla_sounds() -> frozenset[str]:
    """Every audio path (``sounds/...``, no extension) Bedrock's vanilla pack names.

    From Mojang/bedrock-samples, regenerated by scripts/build_vanilla_sounds.py.
    A sound_definitions.json entry naming one of these plays the vanilla file,
    so it is not a dangling reference even though the pack doesn't ship it.
    """
    text = gzip.decompress((_HERE / "bedrock_vanilla_sounds.txt.gz").read_bytes()).decode("utf-8")
    return frozenset(
        line for line in text.splitlines() if line and not line.startswith("#")
    )
