"""Regenerate src/portkit/data/bedrock_vanilla_sounds.txt.gz (#116).

The list is every audio path Bedrock's vanilla resource pack names in its
sound_definitions.json, read from Mojang/bedrock-samples at the commit pinned
for the agent reference (see src/portkit/agent/reference/NOTICE.md). It holds
paths only, no audio and no definitions: the sounds converter uses it to tell
whether a Java vanilla sound (a sounds.json name with no namespace, or
``minecraft:``) has a Bedrock file at the same path. Gzipped (mtime 0, so the
bytes are reproducible) because the plain list is ~145 KB.

    python scripts/build_vanilla_sounds.py           # rewrite the list
    python scripts/build_vanilla_sounds.py --check   # exit 1 if it is stale
"""
from __future__ import annotations

import gzip
import json
import sys
import urllib.request
from pathlib import Path

REPO = "Mojang/bedrock-samples"
COMMIT = "46ba6ea985fb5a92d79a9419198f10dda14c199d"
SOURCE = "resource_pack/sounds/sound_definitions.json"
OUT = Path(__file__).resolve().parents[1] / "src" / "portkit" / "data" / "bedrock_vanilla_sounds.txt.gz"


def build() -> str:
    url = f"https://raw.githubusercontent.com/{REPO}/{COMMIT}/{SOURCE}"
    with urllib.request.urlopen(url, timeout=60) as resp:
        data = json.loads(resp.read())
    definitions = data.get("sound_definitions", data)
    names: set[str] = set()
    for body in definitions.values():
        if not isinstance(body, dict):
            continue
        for sound in body.get("sounds") or []:
            name = sound if isinstance(sound, str) else (sound or {}).get("name")
            if isinstance(name, str) and name.startswith("sounds/"):
                names.add(name)
    header = (
        f"# Bedrock vanilla audio paths, from {REPO}@{COMMIT} {SOURCE}.\n"
        "# Generated by scripts/build_vanilla_sounds.py; do not edit by hand.\n"
    )
    return header + "".join(f"{n}\n" for n in sorted(names))


def main(argv: list[str]) -> int:
    text = build()
    if "--check" in argv:
        current = gzip.decompress(OUT.read_bytes()).decode("utf-8") if OUT.is_file() else ""
        if current != text:
            print(f"{OUT} is stale; rerun scripts/build_vanilla_sounds.py", file=sys.stderr)
            return 1
        print(f"{OUT} is current")
        return 0
    OUT.write_bytes(gzip.compress(text.encode("utf-8"), compresslevel=9, mtime=0))
    print(f"wrote {OUT} ({text.count(chr(10)) - 2} paths)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
